### ISSUE TITLE
Add Rosetta ref2015 energy function for benchmarking

### ISSUE THREAD

**Issue by Seanny123** [sergio-santos-group/ProtoSyn.jl#30]
To get my collaborators to consider this tool as a compelling alternative to Rosetta, I'd like to add the [`ref2015`](https://pubmed.ncbi.nlm.nih.gov/27766851/) energy function to benchmark against. Would this be an acceptable addition to this project?

**Comment by JosePereiraUA** [comment]
This would definitely be a welcomed addition to the project. As a starting point, consider reading the [Calculators section](https://sergio-santos-group.github.io/ProtoSyn.jl/stable/protosyn-api/core/calculators/calculators-section/#Calculators-section) (an in particular the [Creating a custom EnergyFunctionComponent](https://sergio-santos-group.github.io/ProtoSyn.jl/stable/protosyn-api/core/calculators/calculators-section/#Creating-a-custom-EnergyFunctionComponent) section) of the documentation. I would love to help on this, as it has been a long standing goal of the ProtoSyn.jl project.

I have, however, one question: regarding the intellectual property, how easy is it to implement the ref2015 energy function?

**Comment by Seanny123** [comment]
Although Rosetta does have a restrictive license, I've never looked at the `ref2015` implementation and it's not patented. Thus, I think we're legally in the clear if we do a "clean room" implementation.

**Comment by JosePereiraUA** [comment]
Alright. I will take a look at this once I have some time.

**Comment by Seanny123** [comment]
I was thinking it would be a good first issue for me. I'll let you know if I make any progress.

**Comment by JosePereiraUA** [comment]
@Seanny123 I have an update regarding this issue.

I've implemented a (VERY) crude way to use Rosetta's REF15 energy function. Improving on the "plug-and-play" spirit of ProtoSyn, we're now able to call PyRosetta (through the [PyCall.jl](https://github.com/JuliaPy/PyCall.jl) package) and use the default energy function. Check the [dev](https://github.com/sergio-santos-group/ProtoSyn.jl/tree/dev) branch (e51a9c24b44da3e7ba014ad8945c475c425697d5).

In simple terms, this works by printing the ProtoSyn Pose to a file and loading into a Rosetta Pose. It's a very inneficient way of using REF15. But it works. On my machine each call to this component takes around 0.23s, which is unfeasible for most applications. I'll try to work on a better approach. Three ideas that we could implement:

1. For most **non-design** applications (where the nature and number of atoms does not change) a single pose can be maintained throughout the simulation (only updating the atomic positions). This will probably speed up calculations a couple orders of magnitude.
2. Convert from ProtoSyn pose to Rosetta pose without printing to a file (I've tried using the `pose_from_sequence`, the runtime call is halved to around 0.13s). This, however, means that we'd have to take into consideration the terminal cap status, presence of tautomers, hydrogenation status, missing atoms, etc.
3. Another option is to implement the individual energy function components of REF15 natively in ProtoSyn.jl. This would be much faster, especially since ProtoSyn can use the GPU for most pair-wise calculations, but would be extremly difficult to implement correctly, given the lack of proper documentation of Rosetta's code. Still, an option.

For now I hope this solution helps for some quick evaluations and single point measurements.

Usage of this function is extremly simple, just call as a normal energy function component.
```julia
ProtoSyn.Calculators.REF15.calc_ref15(pose, nothing)
```

**Comment by JosePereiraUA** [comment]
Just another quick update: I've implemented the above function as a new Energy Function Component, to use it in an Energy Function (see 05cae3778a19b7f08aa936be467ec2f749ca9b72).

```julia
julia> ef = ProtoSyn.Calculators.EnergyFunction([
    ProtoSyn.Calculators.REF15.get_default_ref15()
])
🗲  Energy Function (1 components):
+----------------------------------------------------------------------+
| Index | Component name                                | Weight (α)   |
+----------------------------------------------------------------------+
| 1     | REF15                                         |      1.000   |
+----------------------------------------------------------------------+
 ● Update forces: false
 ● Selection: Set
 └── TrueSelection (Atom)


julia> ef(pose)
577.7647851944229
```

**Comment by JosePereiraUA** [comment]
I went ahead and implemented option 1 from my [previous comment](https://github.com/sergio-santos-group/ProtoSyn.jl/issues/30#issuecomment-1060764806) (see 5e8b6e8a58da5112a1e9046dc0602a88ee9e7a8e). This allows users to set-up a pre-existing pose and just update the coordinates. 

```julia
julia> pose = ProtoSyn.Peptides.load("2a3d.pdb")
Pose{Topology}(Topology{/2a3d:37366}, State{Float64}:
 Size: 1140
 i2c: false | c2i: false
 Energy: Dict(:Total => Inf)
)

julia> ef = ProtoSyn.Calculators.EnergyFunction([ProtoSyn.Calculators.REF15.get_default_ref15()])
🗲  Energy Function (1 components):
+----------------------------------------------------------------------+
| Index | Component name                                | Weight (α)   |
+----------------------------------------------------------------------+
| 1     | REF15                                         |      1.000   |
+----------------------------------------------------------------------+
 ● Update forces: false
 ● Selection: Set
 └── TrueSelection (Atom)


julia> ProtoSyn.Calculators.REF15.fixate_rosetta_pose!(ef["REF15"], pose)
PyObject <pyrosetta.rosetta.core.pose.Pose object at 0x7f9b5819a970>

julia> ef(pose)
583.2529973244099
```

**Instead of 256ms, this runs in 81ms, which is around 3.15x faster.** However, this only works when the number and nature of atoms remains constant throughout the simulation (i.e. no design effort is being performed).

There is, for some reason, a slight variation in the energy output when updating the atomic coordinates compared to when loading the whole pose. I believe this has to do with some properties (like the hydrogen bond network) not being updated when changing the atomic XYZ coordinates. Most of the necessary updates are done with `pose.update_residue_neighbors()`, but it seems I'm missing something. It shouldn't be too much of a problem, if all comparisons are done within the same conditions, but its something to look into. It's quite frustrating trying to debug these issues: PyRosetta's documentation is ... not ... great ...

**Comment by JosePereiraUA** [comment]
Over the next few weeks/months I'll be focusing on finishing up the documentation/tests for ProtoSyn v1.1 and, as such, won't focus on upgrading this part of the code base. Perhaps some other user takes up the task. For now, I think this solution is sufficient. Closing for now.
