### ISSUE TITLE
load function is saying "no method matching getindex(::Nothing, ::String)"

### ISSUE THREAD

**Issue by kool7d** [sergio-santos-group/ProtoSyn.jl#32]
I am getting an error when I try:
`ProtoSyn.load("data/2vb1.pdb")`

but not with the example pdb:
`ProtoSyn.load("data/2a3d.pdb")`

```ERROR: LoadError: MethodError: no method matching getindex(::Nothing, ::String)
Stacktrace:
 [1] load(#unused#::Type{Float64}, io::IOStream, #unused#::Type{Val{1}})
   @ ProtoSyn C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Core\Methods\io.jl:189
 [2] load(::Type{Float64}, filename::String, ::Type{Val{1}}; bonds_by_distance::Bool)
   @ ProtoSyn C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Core\Methods\io.jl:55
 [3] load(::Type{Float64}, filename::String; bonds_by_distance::Bool)
   @ ProtoSyn C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Core\Methods\io.jl:36
 [4] load(filename::String; bonds_by_distance::Bool)
   @ ProtoSyn C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Core\Methods\io.jl:49
 [5] load(filename::String)
   @ ProtoSyn C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Core\Methods\io.jl:46```

Do the PDB files have to be preprocessed, or are ligands or waters a problem?

**Comment by JosePereiraUA** [comment]
I've replicated this problem by downloading a .pdb file from PDB for the 2VB1 structure. The issue here is that the .pdb file is not in standard format. in some of the lines of the downloaded file, the atom name is outside the allocated column, as exemplified bellow:

`ATOM    122 HH22BARG A   5       1.604  23.953   7.748  0.28 20.86           H`

In this example, the atom name is "HH22B" and the residue name is "ARG". The atom name is therefore outside the allocated character count in a default PDB format. **In order to solve this**, I updated the regular expression being used to parse an `ATOM` entry in a .pdb file to accomodate this specific case. You can change line 178 of the `ProtoSyn.jl/src/Core/Methods/io.jl` from:

`    er = r"\w+\s+(?<aid>\d+)\s+(?<an>\w+)\s+(?<rn>\w+)\s+(?<sn>\S*)\s+(?<rid>\d+)\s+(?<x>-*\d+\.\d+)\s+(?<y>-*\d+\.\d+)\s+(?<z>-*\d+\.\d+)\s+(?:\d+\.\d+)*\s+(?:\d+\.\d+)*\s+\w*\s+(?<as>\w)"
`

to:

`    er = r"\w+\s+(?<aid>\d+)\s+(?<an>\w{1,5})\s*\w*(?<rn>\w{3,})\s+(?<sn>\S*)\s+(?<rid>\d+)\s+(?<x>-*\d+\.\d+)\s+(?<y>-*\d+\.\d+)\s+(?<z>-*\d+\.\d+)\s+(?:\d+\.\d+)*\s+(?:\d+\.\d+)*\s+\w*\s*(?<as>\w)\s*$"
"
`

Or update to the `dev/` branch of the ProtoSyn.jl repository (warning: some extra features are being added in this branch and are still experimental)

Another option is to pre-process the .pdb file and remove any instance where the atom name extends outside the default character spacing.

**Comment by jgreener64** [comment]
Column 17 in an ATOM record is the alternative location identifier and is not part of the atom name: https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

Convention when a single conformation is desired would be to take the alternative location with the highest occupancy and/or with label A.

**Comment by sergiomsantos** [comment]
Please bear in mind that ProtoSyn is not adequate for cleaning PDB structures. Just use a cleaned structure (use whatever strategy is most suited for your needs) and feed it to protosyn.

**Comment by JosePereiraUA** [comment]
Nonetheless, I think that support for the native PDB format is important (I actually had no idea about the existence of the alternative location identified in the PDB format).

I've added experimental support for alternative locations (See this commit: e4b5832a1ee117477ce8d530e4cd6093bf2e86e1).

```julia
julia> pose = ProtoSyn.load("2vb1.pdb", alternative_location = "A");

julia> pose.state[pose.graph[1][1]["HE2"]]
AtomState{Float64}:
 Index: 17
 T: [-2.934, 8.658, 10.791]
 b: 14.143 Å | θ:  1.362 rad (  78.03°) | ϕ:  0.895 rad (  51.26°) | Δϕ:  0.000 rad (   0.00°)
 Changed: false


julia> pose = ProtoSyn.load("2vb1.pdb", alternative_location = "B");

julia> pose.state[pose.graph[1][1]["HE2"]]
AtomState{Float64}:
 Index: 18
 T: [-1.763, 9.419, 11.157]
 b: 14.707 Å | θ:  1.451 rad (  83.12°) | ϕ:  0.870 rad (  49.83°) | Δϕ:  0.000 rad (   0.00°)
 Changed: false
```

Please note the difference in the atom position. If not specified, the default alternative location is "A".
I think that the PDB loading method can always be improved and even though it is definitely not the focus of ProtoSyn, having a good enough parser for most use cases is always a plus.

**Comment by kool7d** [comment]
My workaround I was using (you guys are fast!) is that I load it with BioStructures, select default residues and atoms, and write a new pdb file. Then I change column 17 to a space.

**Comment by JosePereiraUA** [comment]
Yes, pre-processing the PDB file should also work, but it's always a good option to add functionality to ProtoSyn, so thank you for pointing out any short commings you come across! 😄

**Comment by JosePereiraUA** [comment]
Closing this issue! 👍
