### ISSUE TITLE
Some problems with Getting Started example

### ISSUE THREAD

**Issue by kool7d** [sergio-santos-group/ProtoSyn.jl#33]
I get this error when I use `pose = ProtoSyn.Peptides.load("data/2a3d.pdb")`
```
ERROR: LoadError: No atom "C" found in atom Atom{/2a3d:40409/A:1/GLY:2/N:20} bonds list (ProtoSyn.Atom[]).
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] load(::Type{Float64}, filename::String; bonds_by_distance::Bool)
   @ ProtoSyn.Peptides C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Peptides\Methods\io.jl:42
 [3] #load#8
   @ C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Peptides\Methods\io.jl:52 [inlined]
 [4] load(filename::String)
   @ ProtoSyn.Peptides C:\Users\kool7\.julia\packages\ProtoSyn\PZ0MY\src\Peptides\Methods\io.jl:52
   ```

 Other inconsistencies between the example are:

`pose.graph[1,1,"CA"].parent # Atom{/ROOT:37831/OO:0} instead of Atom{/2a3d:11551/A:1/MET:1/N:1}`

`pose.graph[1, 1, "CA"].bonds # ProtoSyn.Atom[] instead of 4-element Array{Atom,1}:
 Atom{/2a3d:11551/A:1/MET:1/N:1}
 Atom{/2a3d:11551/A:1/MET:1/C:3}
 Atom{/2a3d:11551/A:1/MET:1/CB:5}
 Atom{/2a3d:11551/A:1/MET:1/HA:9}`

Everything else appears to work properly. So it looks like the bonding might be the issue?

**Comment by JosePereiraUA** [comment]
I was able to replicate your error, not with the `2a3d.pdb` file from the `examples/data` folder, but from a fresh .pdb file from the PDB database. This is an intended error. ProtoSyn expects a `CONECT` list of records, in the .pdb file, establishing the bonds. The .pdb file extracted from the PDB database (for the 2A3D protein) does not contain the `CONECT` records, and therefore ProtoSyn can't know the correct bonds.

However, the `ProtoSyn.Peptides.load` function has a `bonds_by_distance` flag. When set to true, ProtoSyn will measure the inter-atom distance and predict the atomic bonds. This should be analyzed to make sure the bonds found are correct. In order to solve your issue, please try:

`ProtoSyn.Peptides.load("2a3d.pdb", bonds_by_distance = true)`

Or load a .pdb file with `CONECT` records already established.

---

_A little bit of extra information:_ 

1. ProtoSyn has two main `load` functions: the Core load (simply by calling `ProtoSyn.load`) and the Peptides load (by calling `ProtoSyn.Peptides.load`). The second one expects and gathers extra information, since the loaded structure is now expected to be a peptidic chain. In fact, `ProtoSyn.load` (the core loading method) does not give an error when loading a .pdb file without the `CONECT` records, as they are not expected.

2. When loading the .pdb file with the Core `ProtoSyn.load` method, as you've described, the "CA" parent atom is `Atom{/ROOT:37831/OO:0}` instead of `Atom{/2a3d:11551/A:1/MET:1/N:1}`. This is because, without a `CONECT` record, ProtoSyn automatically assigns the root of the graph as the parent of every atom in the simulation (Check the [Root vs Origin](https://sergio-santos-group.github.io/ProtoSyn.jl/stable/protosyn-api/core/methods/graph/#Root-vs-Origin) section in the ProtoSyn documentation).

**Comment by kool7d** [comment]
Great, this worked.

**Comment by JosePereiraUA** [comment]
No problem. Closing this issue! 👍
