### ISSUE TITLE
Saturation of peptide with hydrogens

### ISSUE THREAD

**Issue by kool7d** [sergio-santos-group/ProtoSyn.jl#36]
Is there a simple way to do this? I want to compare surface meshes for heavy atom only protein structures to those with hydrogens.

**Comment by JosePereiraUA** [comment]
Hi there, @kool7d ! **Yes, it is possible.** Even though this was possible before, I've since implemented a dedicated method, the `add_hydrogens!` function, to do exactly this, so it is easier and more direct. I've updated the master branch with a pull from dev (where I initially implemented the `add_hydrogens!` method, see commit b4e501e470cd31707cc2c77898eb0e736e05a09c and PR #37 ).

I'll try to give you **a quick example**. We can use the 1CTF protein from PDB (it has no hydrogens). With this small update, we can actually download the pose directly from PDB.

```julia
ProtoSyn.Peptides.dowload("1CTF", bonds_by_distance = true)
```

Make sure you use the flag `bonds_by_distance = true`, if your PDB file does not have CONECT records (as is the case with the downloaded 1CTF). If you visualize this pose, it actually has a lot of water molecules and even an SO4 molecule. Even though this is _not_ necessary, I'll just go ahead and clean that up.

```julia
residues = collect(eachresidue(pose.graph));

for i in length(residues):-1:1
   if residues[i].name in ["HOH", "SO4"]
       ProtoSyn.pop_residue!(pose, residues[i])
   end
end
```

It should look something like this.

![1ctf](https://user-images.githubusercontent.com/31994358/142846479-6cc4c71f-3594-4473-ab55-7b31abe6e228.png)

Now, all you need to do is:

```julia
res_lib = ProtoSyn.Peptides.grammar();

ProtoSyn.Peptides.add_hydrogens!(pose, res_lib)
```

And this is the result.

![1ctf2](https://user-images.githubusercontent.com/31994358/142846497-460b4bbc-23bc-43dd-9895-c65b2dba749e.png)

One last step: if your protein, in particular, does not come with a "capped" terminal (with NH3+ and COO- in the terminals), you can re-add them using:

```julia
ProtoSyn.Peptides.cap!(pose)
```

Some notes:

- Under the hood, ProtoSyn is actually mutating each residue _to_ itself, only the new residue has hydrogens included.
- You may realize that the sidechains of the new pose do not align 100% perfectly with the old sidechains. This is because ProtoSyn recovers the dihedral angles of the pre-existing sidechain, but not the angles between each three atoms (or even the bond distances). Naturally, the angles are very similar to the optimal structure, but not 100%. Check if this is something that you absolutely require, it is definetly possible (and quite easy) to recover the angles too, if that is a requirement in your work.

That's it! Hope this helps, be sure to let me know if there is anything else I can help with!

**Comment by JosePereiraUA** [comment]
Seems this question has been answered 😄 
Closing this issue.
Feel free to contact me if you need any extra help!

**Comment by JosePereiraUA** [comment]
**Just quickly re-opening this to add the following:** the previous solution didn't address missing hydrogens in the backbone, only on the sidechain. For that reason, I've since updated the `Peptides.add_hydrogens!` function to now also add missing hydrogens in the backbone of proteins. You can check the changes here: 1ecb4bb453c58645077fd8b2f63c54c99a357e80

_Note: In the case of non-canonical aminoacids, ProtoSyn completly ignores the sidechain, but now still adds any missing hydrogens in the backbone. Adding hydrogens to NCAA is definetly possible, but I think it would be complicated to account for all possible cases and configurations for all hydrogens in all NCAA sidechains._

**Comment by JosePereiraUA** [comment]
**Ok, so this was scratching the back of my mind, and I had to fix it.** See d3f5ecee19f42bc7a0cebbdcd67d9c170c99e031, I added `Peptides.predict_hydrogens!` to try and add hydrogens regardless of having the correct grammar variables or not. This way, for most cases, even NCAAs can be used: I actually required this to add a new aminoacid (MSE) to ProtoSyn's NCAA grammar. `Peptides.predict_hydrogens!` works for common linear structures only: it will fail to predict hydrogen position in circular ring structures (for now, at least).

The most commong usage is, therefore, something like:

```julia
julia> ProtoSyn.Peptides.add_hydrogens!(pose, Peptides.grammar; predict_unknown_aminoacids = true)
```

Any aminoacids identified from the given grammar are guaranteed to use the saved hydrogen positions (in the grammar). Any unknown `Residue` calls `Peptides.predict_hydrogens!`. The predicted hydrogen positions should work for -CH2-, -NH-, -CH3 and -NH3 groups (all terminal heavy atoms of the sidechain have 3 hydrogens, other protonation states are currently not supported and need to be changed manually, for example, using the `pop_atom!` method).

Hopefully this useful for someone ahah!
