### ISSUE TITLE
infer_parenthood! too strict?

### ISSUE THREAD

**Issue by pgbarletta** [sergio-santos-group/ProtoSyn.jl#41]
Hi,
I wanted to try protosyn with a [very short peptide](https://gist.github.com/pgbarletta/e260d842a2a157bac1e4478686a00995), but I can't load it.

```
ERROR: AssertionError: No atom "C" found in atom Atom{/b:14053/B:1/ALA:2/N:6} bonds list (ProtoSyn.Atom[]).
```

For some reason the backbone N atom from the 2nd residue doesn't show up as bonded to the backbone C atom of the previous residue. They're at a 1.5A distance, and I know the structure is good, so I can't tell what's going on.

Thanks!

**Comment by JosePereiraUA** [comment]
Hi there! Thanks for trying out ProtoSyn.
I'm not sure how you're loading up the peptide. I can load it by using the following method:

```
julia> pose = ProtoSyn.Peptides.load("test.pdb", bonds_by_distance = true)
Pose{Topology}(Topology{/test:48835}, State{Float64}:
 Size: 95
 i2c: false | c2i: false
 Energy: Dict(:Total => Inf)
)
```

So, basically, since you're working with a Peptide, you'd want to use the `Peptides` module `load` method (this automatically infers parenthoods, etc.) Since your test `.pdb` file does not have CONECT records, ProtoSyn has to infer the bonds from distance, so you should use the `bonds_by_distance = true` flag.

But you are right in that the error shown is 100% not clear on what's happening. I'll try to fix this and make something more human-readable.

**Comment by pgbarletta** [comment]
oooh, you're right, your example PDB has full CONECT records.
Works now. Thanks!

**Comment by JosePereiraUA** [comment]
Just a quick re-open to say:

- Make sure you're using the [#dev](https://github.com/sergio-santos-group/ProtoSyn.jl/tree/dev) branch. The master branch is completly outdated, I'm finishing up the documentation on the dev side and will merge in the next few weeks.
- I've updated the warning for when a PDB file doesn't have CONECT records (on 0c5c918b376c0c3945db3919b947f5fe5d4680f2). It now looks like this:

```julia
julia> pose = ProtoSyn.Peptides.load("test.pdb", bonds_by_distance = false)
┌ Warning: It seems the loaded pose does not have CONECT records present. Consider setting the `bonds_by_distance` flag to `true`.
└ @ ProtoSyn ~/ProtoSyn.jl/src/Core/Methods/io.jl:396
┌ Warning: Attempted to set-up parenthood in the Atom-level graph, but no bond records were found. Consider loading the pose with the `bonds_by_distance` flag set to `true`.
└ @ ProtoSyn.Peptides ~/ProtoSyn.jl/src/Peptides/Methods/io.jl:65
Pose{Topology}(Topology{/test:15159}, State{Float64}:
 Size: 95
 i2c: false | c2i: false
 Energy: Dict(:Total => Inf)
)
```

**Feel free to open more issues!** And, also, I'd be happy to get feedback on your experience (your issues, what you'd like to see implemented, changes, etc. I'm building this for people to use, so PLEASE, don't be shy, send a message or an e-mail!) :D
